### ISSUE TITLE
Cannot receive stream

### ISSUE THREAD

**Issue by Controlhaus** [web-mech/peerjs-nodejs#1]
When receiving a media stream [like in the peerjs docs](http://peerjs.com/docs/#mediaconnection), the stream object is empty.

mediaConnection.on('stream', function(stream) { ... });    //'stream' is null...

This works fine in a browser.
Is this supported in node?

**Comment by nyvorin** [comment]
I'm pretty sure mediaConnection falls within the "binary" connection types which isn't supported in node atm. https://github.com/web-mech/peerjs-nodejs#a-word-on-connections. There is probably a way to work around it, basically you need Blob and File Api's within node. While there are some libraries out there that facilitate this, peerjs currently uses BlobBuilder api which is deprecated in the browser and non-existent in node land. One day when blobBuilder is removed from browser api's peerjs will have to update that or stop using the dependency that uses it.
